### ISSUE TITLE
Does ON in PyTorch require that batch_size > 1?

### ISSUE THREAD

**Issue by mzhaoshuai** [Cerebras/online-normalization#2]
I test the code with setting `norm_mode="online"` and `batch_size=1`. It told me
```
Traceback (most recent call last):
  File "/home/zhaoshuai/github/online_bn/experiments/resnet/cifar10_main.py", line 148, in <module>
    main(args)
  File "/home/zhaoshuai/github/online_bn/experiments/resnet/cifar10_main.py", line 143, in main
    main_worker(train_loader, val_loader, NUM_CLASSES, args, cifar=True)
  File "/home/zhaoshuai/github/online_bn/experiments/resnet/utils.py", line 97, in main_worker
    train(train_loader, model, criterion, optimizer, epoch, device, args)
  File "/home/zhaoshuai/github/online_bn/experiments/resnet/utils.py", line 138, in train
    output = model(input)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/zhaoshuai/github/online_bn/experiments/resnet/model/model.py", line 211, in forward
    x = self.bn1(x)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/zhaoshuai/github/online_bn/experiments/resnet/online_norm_pytorch/online_norm_2d.py", line 580, in forward
    out = self.ctrl_norm(input)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/zhaoshuai/github/online_bn/experiments/resnet/online_norm_pytorch/online_norm_2d.py", line 486, in forward
    return self.normalizer(input)
  File "/home/zhaoshuai/github/online_bn/experiments/resnet/online_norm_pytorch/online_norm_2d.py", line 409, in forward
    momentum_pow, momentum_batch)
  File "/home/zhaoshuai/github/online_bn/experiments/resnet/online_norm_pytorch/online_norm_2d.py", line 212, in lin_momentum
    input = torch.cat([mu_prev[1:], mu_curr]).transpose(0, 1).unsqueeze(1)
RuntimeError: invalid argument 0: Tensors must have same number of dimensions: got 1 and 2 at /opt/conda/conda-bld/pytorch_1556653099582/work/aten/src/THC/generic/THCTensorMath.cu:62
``` 
The relevant code is 
https://github.com/Cerebras/online-normalization/blob/84895855fb8b099ad8c1266dc325bec41d72ecf5/online-norm/pytorch/online_norm_pytorch/online_norm_2d.py#L212 .

But the code works normally with `norm_mode="online"` and `batch_size=2`.
So I want to know, does ON in PyTorch require that `batch_size > 1`?

**Comment by vchiley** [comment]
Sorry for the super response.

Online Normalization is created as a batch size = 1 normalization technique which uses a time evolving process to estimate the mean and standard deviation for normalization. This means that the samples are processed in order, sequentially. To process the data in order  and sequentially requires a for loop which launches a bunch of really small kernels and the kernel launch time becomes the bottleneck during training. There are 3 ways to get around this issue:
1. concede to running slow code, really slow, like GPU training at batch size 1 slow.
2. write a CUDA kernel which absorbs the loop.
   - fast, efficient but takes engineering hours to get it perfect.
   - I've written a first draft of this, but for the time being we are not releasing that code.
3. realize that this sequential processing can be modeled using convolutions.
   - allows us to linearize the loop and perform it using a cuda call.

We originally chose to do option 3 and that is the code you are trying to run. The mathematics behind the linearization process can be found in [Appendix E of Online Normalization for Training Neural Networks](https://arxiv.org/pdf/1905.05894.pdf). This method does require that you use a batch size > 1. 

The slow loop version is implemented here:
https://github.com/Cerebras/online-normalization/blob/84895855fb8b099ad8c1266dc325bec41d72ecf5/online-norm/pytorch/online_norm_pytorch/online_norm_2d.py#L54

When you initialize `OnlineNormalization`, you can pass the above implementation as the `ctrl_norm` arg. The loop version will be able to do training at any batch size, but is really slow for larger batch sizes.

**Comment by vchiley** [comment]
updt: kernel written for ON. see discussion here https://github.com/Cerebras/online-normalization/pull/1#issuecomment-588330729
